/* Generated by Yosys 0.38+17 (git sha1 cd8e6cbc6, aarch64-apple-darwin21.4-clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

module mycircuit(A, B, C, out);
  wire _0_;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output out;
  wire out;
  assign _0_ = B & A;
  assign out = C & _0_;
endmodule
